apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-zrms
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0022-tenant/tkrw-pr712-0075-0022-app/devfile-sample-zrms@sha256:2b918d92fcf9f6f5507ca9fb0559edfe808434132dbe7f78a93a1111cd0cfbdb
        name: my-nodejs
        resources: {}
status: {}
